import { Inter } from "next/font/google";
import "./globals.scss";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "IQRAA",
  description: "Generated by create next app",
};

export default function RootLayout({ children, signup }) {
  const login = false;

  return (
    <html lang="en">
      <body className={inter.className}>{login ? children : signup}</body>
    </html>
  );
}
