import { Inter } from "next/font/google";
import "./globals.scss";
import LoginPage from "../components/loginPage/LoginPage";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const login = false;

  if (login == true) {
    return (
      <html lang="en">
        <body className={inter.className}>{children}</body>
      </html>
    );
  } else {
    return (
      <>
        <html lang="en">
          <body>
            <LoginPage />
          </body>
        </html>
      </>
    );
  }
}
